// Fausses données utilisées pour tester le tableau de bord sans matériel réel.
// Chaque nœud a son propre profil (NORMAL / WARNING / DANGER) pour démontrer
// les trois états possibles simultanément.

export const fakeNodeData = {
    "esp32-1": {
        system: {
            cpu_temperature: 45,
            total_ram: 320000,
            free_ram: 210000,
            used_ram: 110000,
            minimum_free_ram: 200000,
            cpu_frequency: 240,
            cpu_cores: 2,
            active_core: 1,
            chip_model: "ESP32-D0WD-V3",
            chip_revision: 3,
            flash_size: 4194304,
            sketch_size: 1038090,
            sdk_version: "ESP-IDF",
            uptime: 1560,
            reconnects: 0,
            status: "NORMAL",
        },
        sensor: {
            external_temperature: 24,
            humidity: 0,
            gas_level: 180,
            gas_alarm: 1,
            status: "NORMAL",
        },
        network: {
            ip_address: "192.168.1.189",
            wifi_status: "Connected",
            wifi_signal: -52,
            gateway: "192.168.1.1",
            subnet: "255.255.255.0",
            dns: "192.168.1.1",
            mac_address: "1C:69:20:95:89:38",
            hostname: "ESP32-Monitor-1",
        },
    },

    "esp32-2": {
        system: {
            cpu_temperature: 65,
            total_ram: 320000,
            free_ram: 96000,
            used_ram: 224000,
            minimum_free_ram: 90000,
            cpu_frequency: 240,
            cpu_cores: 2,
            active_core: 0,
            chip_model: "ESP32-D0WD-V3",
            chip_revision: 3,
            flash_size: 4194304,
            sketch_size: 1041200,
            sdk_version: "ESP-IDF",
            uptime: 2870,
            reconnects: 1,
            status: "WARNING",
        },
        sensor: {
            external_temperature: 33,
            humidity: 0,
            gas_level: 420,
            gas_alarm: 1,
            status: "WARNING",
        },
        network: {
            ip_address: "192.168.1.190",
            wifi_status: "Connected",
            wifi_signal: -68,
            gateway: "192.168.1.1",
            subnet: "255.255.255.0",
            dns: "192.168.1.1",
            mac_address: "24:6F:28:AA:11:02",
            hostname: "ESP32-Monitor-2",
        },
    },

    "esp32-3": {
        system: {
            cpu_temperature: 82,
            total_ram: 320000,
            free_ram: 58590,
            used_ram: 261410,
            minimum_free_ram: 48830,
            cpu_frequency: 240,
            cpu_cores: 2,
            active_core: 1,
            chip_model: "ESP32-D0WD-V3",
            chip_revision: 3,
            flash_size: 4194304,
            sketch_size: 1055000,
            sdk_version: "ESP-IDF",
            uptime: 3720,
            reconnects: 2,
            status: "DANGER",
        },
        sensor: {
            external_temperature: 44,
            humidity: 1,
            gas_level: 720,
            gas_alarm: 0,
            status: "DANGER",
        },
        network: {
            ip_address: "192.168.1.191",
            wifi_status: "Connected",
            wifi_signal: -83,
            gateway: "192.168.1.1",
            subnet: "255.255.255.0",
            dns: "192.168.1.1",
            mac_address: "A0:20:A6:0C:44:19",
            hostname: "ESP32-Monitor-3",
        },
    },
};

export const fakeNodes = [
    {
        id: "fake-esp32-1",
        node_name: "esp32-1",
        node_type: "esp32",
        added_at: new Date().toISOString(),
    },
    {
        id: "fake-esp32-2",
        node_name: "esp32-2",
        node_type: "esp32",
        added_at: new Date().toISOString(),
    },
    {
        id: "fake-esp32-3",
        node_name: "esp32-3",
        node_type: "esp32",
        added_at: new Date().toISOString(),
    },
    {
        id: "fake-pi-1",
        node_name: "raspberry-pi-1",
        node_type: "raspberry",
        added_at: new Date().toISOString(),
    },
];
